const {test}=require('node:test');
const assert=require('node:assert/strict');
const {randomUUID}=require('node:crypto');
const {authDatabase}=require('./auth-test-db.cjs');
test('authenticated grants, scoped records and movement custody survive role hardening',async()=>{
 const f=await authDatabase(),{db,actors:a,query,rpc}=f;
 try{
  const act=(user,action,payload,operation=randomUUID())=>rpc(user,'mcpa_movement_action',{p_action:action,p_payload:payload,p_operation_id:operation});
  await assert.rejects(()=>rpc(null,'mcpa_movement_snapshot'),/permission denied/);
  await assert.rejects(()=>rpc(a.inactive,'mcpa_movement_snapshot'),/active authorized/);
  await assert.rejects(()=>rpc(a.secretary,'mcpa_movement_snapshot'),/restricted/);
  assert.equal((await query(a.sky,'select * from equipment')).rows.length,0);
  assert.equal((await query(a.handler,'select * from equipment')).rows.length,6);
  await assert.rejects(()=>query(a.sky,'select * from profiles'),/permission denied/);
  await assert.rejects(()=>rpc(a.sky,'mcpa_accounts'),/Admin access/);
  const account={p_id:a.inactive.id,p_name:a.inactive.name,p_role:'engineer',p_status:'active',p_auth_user_id:a.inactive.authId};
  await assert.rejects(()=>rpc(a.sky,'mcpa_save_account',account),/Admin access/);
  await assert.rejects(()=>rpc(a.admin,'mcpa_save_account',{...account,p_id:a.admin.id,p_auth_user_id:a.admin.authId}),/own administrator/);
  await assert.rejects(()=>rpc(a.admin,'mcpa_save_account',{...account,p_auth_user_id:randomUUID()}),/Auth account first/);
  assert.equal(await rpc(a.admin,'mcpa_save_account',account),a.inactive.id,'Account activation preserves the historical profile ID');
  assert.equal((await rpc(a.inactive,'mcpa_my_profile')).account_status,'active');
  await rpc(a.admin,'mcpa_save_account',{...account,p_status:'inactive'});
  await assert.rejects(()=>rpc(a.inactive,'mcpa_movement_snapshot'),/active authorized/);
  await assert.rejects(()=>query(a.sky,"update profiles set role='admin'"),/permission denied/);
  await assert.rejects(()=>query(a.admin,"update equipment set current_holder_id=$1",[a.sky.id]),/permission denied/);
  await assert.rejects(()=>query(a.admin,'select mcpa_auth_private.mcpa_movement_action($1,$2,$3)',['createRequest',{},randomUUID()]),/permission denied/);
  await assert.rejects(()=>act(a.admin,'createRequest',{}),/not permitted/);
  await assert.rejects(()=>act(a.sky,'approveRequest',{actor:a.admin}),/not permitted/);
  const request=await act(a.sky,'createRequest',{toolIds:['TOOL-001'],destination:'Casa Buena',purpose:'Structural works',actor:a.admin});
  assert.equal(request.requester,a.sky.name,'Forged actor is ignored');
  let snapshot=await rpc(a.admin,'mcpa_movement_snapshot');
  assert.equal(snapshot.tools.find(t=>t.id==='TOOL-001').holder,'');
  await act(a.admin,'approveRequest',{id:request.id});
  const transfer=await act(a.admin,'releaseRequest',{id:request.id});
  snapshot=await rpc(a.admin,'mcpa_movement_snapshot');assert.equal(snapshot.tools.find(t=>t.id==='TOOL-001').holder,'');
  await assert.rejects(()=>act(a.admin,'receiveTransfer',{id:transfer.id}),/not permitted/);
  await assert.rejects(()=>act(a.pau,'receiveTransfer',{id:transfer.id}),/named receiver/);
  await assert.rejects(()=>act(a.sky,'receiveTransfer',{id:transfer.id,inspections:[{toolId:'TOOL-001',condition:'good'}]}),/Test every/);
  await assert.rejects(()=>act(a.sky,'receiveTransfer',{id:transfer.id,inspections:[{toolId:'TOOL-001',condition:'damaged',notes:'Guard broken',tested:true,disposition:'declined'}]}),/Explicitly accept custody/);
  const payload={id:transfer.id,inspections:[{toolId:'TOOL-001',condition:'good',tested:true}]}, operation=randomUUID();
  await act(a.sky,'receiveTransfer',payload,operation);await act(a.sky,'receiveTransfer',payload,operation);
  snapshot=await rpc(a.admin,'mcpa_movement_snapshot');assert.equal(snapshot.tools.find(t=>t.id==='TOOL-001').holder,a.sky.name);
  assert.ok(snapshot.activity.length>=4);
  await act(a.sky,'createReturn',{toolIds:['TOOL-001'],destination:'Main Warehouse',conditions:[{toolId:'TOOL-001',condition:'damaged',notes:'Guard broken'}],notes:'Return'});
  snapshot=await rpc(a.admin,'mcpa_movement_snapshot');const repair=snapshot.repairs.find(r=>r.toolId==='TOOL-001');assert.ok(repair);
  assert.equal(snapshot.tools.find(t=>t.id==='TOOL-001').holder,a.sky.name,'Damaged return retains accountability');
  await act(a.admin,'startRepair',{id:repair.id});await act(a.admin,'completeRepair',{id:repair.id,destination:'Main Warehouse',notes:'Guard replaced and checked'});
  await db.query('update sites set assigned_engineer_id=$1 where id=$2',[a.architect.id,f.sites.main]);
  await act(a.architect,'createRequest',{toolIds:['TOOL-001'],destination:'Main Warehouse',purpose:'Architect request'});
  assert.ok((await rpc(a.architect,'mcpa_movement_snapshot')).requests.some(r=>r.requester===a.architect.name));
  assert.ok(!(await rpc(a.pau,'mcpa_movement_snapshot')).tools.some(t=>t.id==='TOOL-002'),'Unrelated deployed equipment is not disclosed');
  await assert.rejects(()=>query(a.sky,'select public.consumables_save_item($1,null,$2,$3,0,0)',[randomUUID(),'Pipe','m']),/Materials access/);
  await query(a.secretary,'select public.consumables_save_item($1,null,$2,$3,0,0)',[randomUUID(),'Pipe','m']);
  assert.equal((await query(a.secretary,'select * from consumables')).rows.length,1);
  assert.equal((await query(a.sky,'select * from consumables')).rows.length,0);
  await db.query("update profiles set account_status='inactive' where id=$1",[a.sky.id]);
  await assert.rejects(()=>rpc(a.sky,'mcpa_movement_snapshot'),/active authorized/);
  await assert.rejects(()=>act(a.sky,'reportMissing',{toolId:'TOOL-002',notes:'Missing'}),/active authorized/);
  await db.exec('grant update(current_holder_id) on equipment to authenticated; grant select(auth_user_id) on profiles to authenticated;');
  await db.exec(f.migration);
  await assert.rejects(()=>query(a.admin,'update equipment set current_holder_id=$1',[a.sky.id]),/permission denied/);
  await assert.rejects(()=>query(a.admin,'select auth_user_id from profiles'),/permission denied/);
  assert.ok((await rpc(a.admin,'mcpa_movement_snapshot')).activity.length>=7,'Rerun retains audit records');
 }finally{await f.close();}
});
